### ISSUE TITLE
Connecting to node 172.17.0.2:6379: [ERR] Sorry, can't connect to node 172.17.0.2:6379

### ISSUE THREAD

**Issue by vrudikov** [vishnudxb/docker-redis-cluster#1]
Hi. Got this error on startup. Any ideas how it can be fixed?

```
/src # cd redis-replica-3/
/src/redis-replica-3 # tail redis-replica-3.log 
16:M 18 May 18:51:54.978 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
16:M 18 May 18:51:54.978 * The server is now ready to accept connections on port 6384
58:M 18 May 19:24:03.042 # Creating Server TCP listening socket *:6384: bind: Address in use
64:M 18 May 19:24:04.072 # Creating Server TCP listening socket *:6384: bind: Address in use
70:M 18 May 19:24:06.099 # Creating Server TCP listening socket *:6384: bind: Address in use
85:M 18 May 19:24:09.126 # Creating Server TCP listening socket *:6384: bind: Address in use
104:M 18 May 19:26:07.002 # Creating Server TCP listening socket *:6384: bind: Address in use
110:M 18 May 19:26:08.028 # Creating Server TCP listening socket *:6384: bind: Address in use
116:M 18 May 19:26:10.050 # Creating Server TCP listening socket *:6384: bind: Address in use
122:M 18 May 19:26:13.076 # Creating Server TCP listening socket *:6384: bind: Address in use
```

**Comment by vrudikov** [comment]
It seems to be some security issues. i received this message when tried to run
`redis-cli -h 172.17.0.2 -p 6379`

`
(error) DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
`

**Comment by vishnudxb** [comment]
@vrudikov  You're right, it is because of the protected mode.  I had fixed it, please try now.

    $ redis-cli -h 127.0.0.1 -p 6379 cluster nodes       
    48ba8891752ba6780dc49f5cefdf50cbc9c6879e 172.17.0.2:6383 slave 883b933a5dc06b88b95e78030a0bdd81bf8e49fd 0 1495220667874 5 connected
    9b33bec36ce63e0ee91dc69735eb98a165bae7b8 172.17.0.2:6379 myself,master - 0 0 1 connected 0-5460
    d19c2bed2b000989c496530169ca46a566e34986 172.17.0.2:6382 slave 9b33bec36ce63e0ee91dc69735eb98a165bae7b8 0 1495220667874 4 connected
    534c87f8147ebc4c8e9a22067fd989a2b94b0326 172.17.0.2:6381 master - 0 1495220667874 3 connected 10923-16383
    883b933a5dc06b88b95e78030a0bdd81bf8e49fd 172.17.0.2:6380 master - 0 1495220667874 2 connected 5461-10922
    02e733f264a8bacb0ed8f9d9fd283d57a23954cd 172.17.0.2:6384 slave 534c87f8147ebc4c8e9a22067fd989a2b94b0326 0 1495220667874 6 connected
