### ISSUE TITLE
Question: Internal and external IP conflict when using phpredis

### ISSUE THREAD

**Issue by boesing** [vishnudxb/docker-redis-cluster#5]
Hey there,

I am the maintainer of [laminas/laminas-cache-storage-adapter-redis](https://github.com/laminas/laminas-cache-storage-adapter-redis) and use your provided container in our github actions for over a year now.

It worked without problems for more than a year but somehow stopped working between October 10th and October 28th as the last successful build was on October 10th.

However, this repository did not change since May and thus I am totally aware that this might not be the problem here.
It seems that the problem is that the cluster internally does bind to the public IP (using `bind 0.0.0.0`) while communicating internally via private IPs (thats just an assumption, there is actually no real way to verify this properly - at least for me).

Thats also what phpredis issue points out:
https://github.com/phpredis/phpredis/issues/1918#issuecomment-768071455

So "maybe" something has changed for github actions exposing IPs via `service` identifier or whatever.

### The question is: 

Is there a way to somehow synchronizing both IPs (private & public) so that the clusters are synchronizing themselves via the same IP? 
That would actually help us fixing our builds.
I am happy to provide a PR once you are open for that kind of change.

Thanks in advance!

**Comment by vishnudxb** [comment]
@boesing  Instead of using it like this https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/2.4.x/.github/workflows/continuous-integration.yml#L33  Did you try the github action https://github.com/vishnudxb/redis-cluster ?

**Comment by vishnudxb** [comment]
@boesing  This one is working https://github.com/laminas/laminas-cache-storage-adapter-redis/actions/runs/3634723557/jobs/6133116175
