### ISSUE TITLE
New release with 7.4.0

### ISSUE THREAD

**Issue by mrniko** [vishnudxb/docker-redis-cluster#8]
Hi,

Could you please make a new release with the latest version?

**Comment by vishnudxb** [comment]
@mrniko Done, created new release with the latetst version.

**Comment by vishnudxb** [comment]
Reopened it, noticed the alpine doesn't have the latest version yet in the package. Checking to do it with the source

**Comment by vishnudxb** [comment]
@mrniko  Updated the image to use redis 7.4.0. Next week will update it to use 7.4.6. 
![Screenshot 2024-08-14 at 9 19 29 AM](https://github.com/user-attachments/assets/dbc2de90-d93b-4f00-99ad-9bb41f38dea6)

**Comment by mrniko** [comment]
Thank you!

> Reopened it, noticed the alpine doesn't have the latest version yet in the package

That's expected since Redis isn't OSS since 7.4 version
